import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { GeistSans } from "geist/font/sans"
import { GeistMono } from "geist/font/mono"

import "./globals.css"
import { ThemeProvider } from "../components/theme-provider"
import Navbar from "../components/navbar"
import { AnimatedBlob } from "../components/animBlob"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "PortFolio",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${GeistMono.className} overflow-y-scroll overflow-x-hidden`}
      >
        <ThemeProvider attribute="class" disableTransitionOnChange>
          {/* <Stars /> */}
          <Navbar />
          <AnimatedBlob />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
